#PBS -S /bin/bash
#PBS -N addiction_public_disease_gsmr_reverse
#PBS -A UQ-IMB-CNSG
#PBS -o /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/reverse/stdout_addiction_public_disease_gsmr_reverse
#PBS -e /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/reverse/stderr_addiction_public_disease_gsmr_reverse
#PBS -l select=1:ncpus=1:intel=True:mem=22GB
#PBS -l walltime=23:00:00

cd /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/reverse/

# this script will run GCTA-integrated GSMR
gcta="/shares/compbio/Group-Yang/uqzzhu1/bin/gcta64_20Mar2020"
exposure_file="../Outcome_public_disease.list"
outcome_file="../Exposure.list"
output_path="addiction_public_disease_gsmr_reverse"
geno_file="../gsmr_ref_UKB.txt"

$gcta --gsmr2-beta-2 --mbfile ${geno_file}  --gsmr-file ${exposure_file} ${outcome_file} --gsmr-direction 0 --heidi-thresh 0.01 --heidi-filter-thresh 0 --gsmr-snp-min 5 --clump-r2 0.01 --out ${output_path} --effect-plot


