#PBS -S /bin/bash
#PBS -N AC_not_ascertained_log2_adj_longitudinal_removed_underreport_all_mtCOJO
#PBS -A UQ-IMB-CNSG
#PBS -o /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/mtCOJO/stderr_AC_not_ascertained_log2_adj_longitudinal_removed_underreport_all_mtCOJO
#PBS -e /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/mtCOJO/stdout_AC_not_ascertained_log2_adj_longitudinal_removed_underreport_all_mtCOJO
#PBS -l select=1:ncpus=7:intel=True:mem=12GB
#PBS -l walltime=3:00:00

cd /shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/mtCOJO/

gcta="/shares/compbio/Group-Yang/uqzzhu1/bin/gcta64_24Jan2019"
geno="/shares/compbio/Group-Yang/a.xue/proj/addiction/GSMR/gsmr_ref_UKB.txt"
ld="/shares/compbio/Group-Yang/a.xue/app/ldsc/eur_w_ld_chr/"
out="AC_not_ascertained_log2_adj_longitudinal_removed_underreport_all_mtCOJO"

$gcta --gsmr-beta --mbfile $geno --mtcojo-file AC_not_ascertained_log2_adj_longitudinal_removed_underreport_all_mtCOJO.list --heidi-thresh 0.01 0.01 --gsmr-snp-min 1 --clump-r2 0.01 --ref-ld-chr $ld --w-ld-chr $ld --out ${out} >> ${out}.log 2>&1 --thread-num 7


